// Counter Action
export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"
export const RESET_COUNTER = "RESET_COUNTER"

// Article Action
export const FETCHING_ARTICLE_REQUEST = "FETCHING_ARTICLE_REQUEST"
export const FETCHING_ARTICLE_SUCCESS = "FETCHING_ARTICLE_SUCCESS"
export const FETCHING_ARTICLE_FAILURE = "FETCHING_ARTICLE_FAILURE"
